[package]
name = "puremd"
version = "1.1.0"
description = "Minimal pure local Markdown viewer/editor"
authors = ["PureMD"]
license = "MIT"
repository = "https://github.com/quetzaone/puremd"
edition = "2021"

[lib]
name = "puremd_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"
percent-encoding = "=2.3.2"
imagesize = { version = "=0.15.0", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-single-instance = "=2.4.2"
url = "=2.5.8"
windows = { version = "=0.61.3", features = ["Win32_Foundation", "Win32_Networking_WinHttp", "Win32_Security_Cryptography", "Win32_UI_Controls_Dialogs"] }
